# config.yaml

# --- General Parameters ---
amp: "200s"
station_ids_200s: [14, 17, 19, 30]
station_ids_100s: [13, 15, 18]

loading_data_type: "new_chi_above_curve"
num_above_curve_events: 10000 # if training, check train_cut

noise_rms_200s: 22.53  # units.mV will be applied in code
noise_rms_100s: 20.0

# --- Simulation and Templates ---
# note: When I start making my own sim, the events will be saved locally to base folder /pub/tangch3/ARIANNA/DeepLearning/simulated_events  
base_sim_rcr_folder: "/dfs8/sbarwick_lab/ariannaproject/rricesmi/simulatedRCRs/"                        # example subfolder: ./200s/5.28.25/
sim_rcr_date: "5.28.25"
noise_enabled: True
base_sim_backlobe_folder: "/dfs8/sbarwick_lab/ariannaproject/rricesmi/numpy_arrays/simulatedBacklobes/" # example subfolder: ./200s_10.25.24/
sim_backlobe_date: "10.25.24"

rcr_single_template_folder: "/dfs8/sbarwick_lab/ariannaproject/rricesmi/numpy_arrays/templates/reflectedCR_template_{series}eries.pkl" 
rcr_multi_template_folder: "/pub/tangch3/ARIANNA/DeepLearning/RCR_templates/{date}/" # downloaded from https://github.com/rricesmith/ReflectionAnalysis/tree/main/DeepLearning/templates/RCR/3.29.25
rcr_multi_template_date: "3.29.25" 

2016_backlobe_template_folder: "/dfs8/sbarwick_lab/ariannaproject/rricesmi/numpy_arrays/templates/confirmed2016Templates/"


# --- Station data ---
coincidence_events_path: "/pub/tangch3/ARIANNA/DeepLearning/refactor/coincidence_events/filtered_coinc.pkl"

1000_above_curve_data_folder: "/pub/tangch3/ARIANNA/DeepLearning/refactor/station_data/above_curve_data/1000evt_8.25.25/" 
5000_above_curve_data_folder: "/pub/tangch3/ARIANNA/DeepLearning/refactor/station_data/above_curve_data/5000evt_8.22.25/" 
10000_above_curve_data_folder: "/pub/tangch3/ARIANNA/DeepLearning/refactor/station_data/above_curve_data/10000evt_8.19.25/"

all_station_data: "/pub/tangch3/ARIANNA/DeepLearning/refactor/station_data/all_data/5.20.25/" # not raw, passed noise cuts


# --- Neural Net Training Inputs & Outputs
# base_model_path: "/pub/tangch3/ARIANNA/DeepLearning/refactor/models/"
# base_plot_path: "/pub/tangch3/ARIANNA/DeepLearning/refactor/plots/"
base_model_path: "/dfs8/sbarwick_lab/ariannaproject/tangch3/models/"
base_plot_path: "/dfs8/sbarwick_lab/ariannaproject/tangch3/plots/"

# Training
if_1D: False # currently used in checks.py to evaluate transposed events
prefix : "1D_CNN_HGQ"
train_cut: 8000
early_stopping_patience: 5
keras_epochs: 50
keras_batch_size: 500
verbose_fit: 1
model_filename_template: "{timestamp}_{amp}_{prefix}_model_2Layer.h5"

# Evaluation
output_cut_value: 0.9
history_filename_template: "{timestamp}_{amp}_{prefix}_model_2Layer_history.pkl"
loss_plot_filename_template: "{timestamp}_{amp}_{prefix}_loss_plot_2Layer.png"
accuracy_plot_filename_template: "{timestamp}_{amp}_{prefix}_accuracy_plot_2Layer.png"
tsne_plot_filename_template: "{timestamp}_{amp}_tsne_feature_space_{prefix}_2Layer.png"
histogram_filename_template: "{timestamp}_{amp}_{prefix}_histogram.png"

# DANN specific
if_dann: False # currently used in checks.py to load dann model
lambda_adversary: 0.001
input_shape: [4, 256, 1]
